# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Clean Albums' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clean Albums
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'ObjectMapper'
  pod 'Kingfisher'

  target 'Clean AlbumsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Clean AlbumsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
