//
//  ShowOrderInteractor.swift
//  CleanStore
//
//  Created by Anton on 17.05.2018.
//  Copyright (c) 2018 fynjyass. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowOrderBusinessLogic {
    func getOrder(request: ShowOrder.GetOrder.Request)
}

protocol ShowOrderDataStore {
    var order: Order! {get set}
}

class ShowOrderInteractor: ShowOrderBusinessLogic, ShowOrderDataStore {
    var presenter: ShowOrderPresentationLogic?
    var order: Order!
    
    func getOrder(request: ShowOrder.GetOrder.Request) {
        let response = ShowOrder.GetOrder.Response(order: order)
        presenter?.presentOrder(response: response)
    }
    
  
}
