//
//  ShowOrderModels.swift
//  CleanStore
//
//  Created by Anton on 17.05.2018.
//  Copyright (c) 2018 fynjyass. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowOrder {
  
  enum GetOrder {
    
    struct Request {
        
    }
    
    struct Response {
        var order: Order
    }
    
    struct ViewModel {
        struct DisplayedOrder {
            var id: String
            var date: String
            var email: String
            var name: String
            var total: String
        }
        
        var displayedOrder: DisplayedOrder

    }
  }
}
