//
//  CreateOrderModels.swift
//  CleanStore
//
//  Created by Anton Aleksieiev on 5/15/18.
//  Copyright (c) 2018 fynjyass. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateOrder
{
  // MARK: Use cases
    enum FormatExpirationDate {
        struct Request {
            var date: Date
        }
        struct Response {
            var date: Date
        }
        struct ViewModel {
            var date: String
        }
    }
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
