//
//  ListOrdersRouter.swift
//  CleanStore
//
//  Created by Anton on 17.05.2018.
//  Copyright (c) 2018 fynjyass. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListOrdersRoutingLogic {
    func routeToCreateOrder(segue: UIStoryboardSegue?)
    func routeToShowOrder(segue: UIStoryboardSegue?)
}

protocol ListOrdersDataPassing {
  var dataStore: ListOrdersDataStore? { get }
}

class ListOrdersRouter: NSObject, ListOrdersRoutingLogic, ListOrdersDataPassing {
  weak var viewController: ListOrdersViewController?
  var dataStore: ListOrdersDataStore?
  
  // MARK: Routing
    func routeToCreateOrder(segue: UIStoryboardSegue?) {
        let destinationVC = segue!.destination as! CreateOrderViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToCreateOrder(source: dataStore!, destination: &destinationDS)
        navigateToCreateOrder(source: viewController!, destination: destinationVC)
    }

    func routeToShowOrder(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ShowOrderViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowOrder(source: dataStore!, destination: &destinationDS)
        } else {
            let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "ShowOrderViewController") as! ShowOrderViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowOrder(source: dataStore!, destination: &destinationDS)
            navigateToShowOrder(source: viewController!, destination: destinationVC)
        }
    }

    func passDataToCreateOrder(source: ListOrdersDataStore, destination: inout CreateOrderDataStore) {
        
    }
    
    func navigateToCreateOrder(source: ListOrdersViewController, destination: CreateOrderViewController) {
        
    }
    
    func passDataToShowOrder(source: ListOrdersDataStore, destination: inout ShowOrderDataStore) {
        let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
        destination.order = source.orders?[selectedRow!]
    }
    
    func navigateToShowOrder(source: ListOrdersViewController, destination: ShowOrderViewController) {
        source.show(destination, sender: nil)
    }
    
}
